name: CI - Build

on:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Build VPP Detect (Obj-C)
        run: python3 pkg.py

      - name: Compress Packages
        run: |
          ditto -c -k --sequesterRsrc --keepParent 'vpp-detect' 'VPP Detection (Obj-C).zip'
          ditto -c -k --sequesterRsrc --keepParent 'Packaging/Install-VPP-Detect.pkg' 'VPP Detection (Obj-C).pkg.zip'
          ditto -c -k --sequesterRsrc --keepParent 'Packaging/Uninstall-VPP-Detect.pkg' 'VPP Detection Uninstall (Obj-C).pkg.zip'
          ditto -c -k --sequesterRsrc --keepParent 'vpp-detect.sh' 'VPP Detection (ZSH).zip'

      - name: Upload VPP Detect (Obj-C) (artifact)
        uses: actions/upload-artifact@v2
        with:
            name: VPP Detection (Obj-C) (artifact)
            path: VPP Detection (Obj-C).zip

      - name: Upload VPP Detect (ZSH) (artifact)
        uses: actions/upload-artifact@v2
        with:
            name: VPP Detection (ZSH) (artifact)
            path: VPP Detection (ZSH).zip

      - name: Upload VPP Detection (Obj-C) (pkg) (artifact)
        uses: actions/upload-artifact@v2
        with:
            name: VPP Detection (Obj-C) (pkg) (artifact)
            path: VPP Detection (Obj-C).pkg.zip

      - name: Upload VPP Detection Uninstall (Obj-C) (pkg) (artifact)
        uses: actions/upload-artifact@v2
        with:
            name: VPP Detection Uninstall (Obj-C) (pkg) (artifact)
            path: VPP Detection Uninstall (Obj-C).pkg.zip

      - name: Upload VPP Detect (Obj-C) (on release)
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: VPP Detection (Obj-C).zip
          tag: ${{ github.ref }}
          file_glob: true

      - name: Upload VPP Detection (ZSH) (on release)
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: VPP Detection (ZSH).zip
          tag: ${{ github.ref }}
          file_glob: true


      - name: Upload VPP Detection (Obj-C) (pkg) (on release)
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: VPP Detection (Obj-C).pkg.zip
          tag: ${{ github.ref }}
          file_glob: true

      - name: Upload VPP Detection Uninstall (Obj-C) (pkg) (on release)
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: VPP Detection Uninstall (Obj-C).pkg.zip
          tag: ${{ github.ref }}
          file_glob: true